FROM node:12.13.0-alpine

COPY ./dist ./dist
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i node cross-env

EXPOSE 8081
ENV PORT 8081
ENV NODE_ENV production

CMD ["npm", "run", "start:prod"]
